apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bios
  labels:
    version: ${VERSION}
spec:
  serviceName: bios
  replicas: 1
  selector:
    matchLabels:
      app: bios
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: bios
        version: ${VERSION}
    spec:
      containers:
        - name: nodeos
          image: ${DOCKER_REGISTRY}/${CDT_IMAGE_NAME}:${EOSIO_VERSION}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: lacchain-secrets
          env:
            - name: DATA_DIR
              value: /data/nodeos
            - name: CONFIG_DIR
              value: /data/nodeos/config
          ports:
            - name: p2p
              protocol: TCP
              containerPort: 9876
            - name: http
              protocol: TCP
              containerPort: 8888
          # livenessProbe:
          #   tcpSocket:
          #     port: p2p
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          #   periodSeconds: 15
          # readinessProbe:
          #   tcpSocket:
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          volumeMounts:
            - name: data-directory
              mountPath: /data/nodeos
            - name: scripts
              mountPath: /opt/scripts
            - name: schedule
              mountPath: /opt/schedule
            - name: genesis
              mountPath: /opt/genesis
      volumes:
        - name: scripts
          configMap:
            name: bios-config
            defaultMode: 0755
        - name: schedule
          configMap:
            name: schedule-config
        - name: genesis
          configMap:
            name: genesis-config
  volumeClaimTemplates:
    - metadata:
        name: data-directory
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: lacchain
        resources:
          requests:
            storage: 50Gi
